[tasks.dev]
description = "run web server in dev mode"
run = "cargo run"

[tasks.test]
description = "run tests"
run = "cargo test"

[tasks.outdated]
description = "list latest version of installed crates"
run = "cargo outdated"
